### ISSUE TITLE
Common.js in the browser

### ISSUE THREAD

**Issue by notslang** [componentjs/builder.js#103]
How does component deal with the [issues](http://requirejs.org/docs/commonjs.html#intro) caused by Common.js being synchronous, yet also being used to build modules that run on the web?

in the blog post by @visionmedia, he says:

```
I completely understand that perhaps [neither] AMD nor sync-style requires
are perfect, but if we pick one we can easily translate scripts to an
async style for production builds if necessary.
```

But, the r.js converter [fails](https://github.com/jrburke/r.js#convert-commonjs-modules) with any Common.js module that has dynamic requires (or a few other characteristics), because Require.js is asynchronous... I feel that relying on a conversion tool like this would make component really buggy. And that seems like an unnecessary issue since require.js modules can already run in node/rhino without conversion... but yeah... I digress.

**Comment by timoxley** [comment]
I don't think many (any) people are using the r.js converter. Manually converting a codebase to be compatible with components is usually trivial, so long as the code behaves and doesn't couple tightly with the global namespace.

**Comment by notslang** [comment]
I'm not talking about converting existing modules to be compatible with components, I'm talking about how components are compatible with a web-browser environment when they're tied to a synchronous module loader.

**Comment by timoxley** [comment]
Not sure what the issue is. You load all the code as a single bundled js file. Life is simple. Miss out on a few things like caching, but not a big deal and not an unsolvable problem if it's really required. TJ addresses a similar question here: https://github.com/component/component/issues/229#issuecomment-12290596

**Comment by timoxley** [comment]
here's another option if you're concerned with build sizes: https://github.com/component/component/issues/358#issuecomment-19519485

**Comment by anthonyshort** [comment]
Guessing you're at that stage where you're deciding on RJS or CJS. 

CommonJS is synchronous, but it combines everything into a single file and that's what you use in the browser. AMD loads everything on the fly. However, for production, people always combine all the AMD files into a single file anyway but you're stuck with the ugly AMD syntax.

So either way you need a build tool.

You will very, very rarely need to do dynamic requires. I don't think I've ever needed to do it. The real problem are circular dependencies. They're a bitch. With AMD you need to use the CJS syntax to get circular dependencies to work. Example of when you might need this, a Collection requires a Model, and a Model requires the Collection to create dynamic relationships. KABOOM. Everything explodes. 

Although, circular dependencies can usually be avoided with better code.

Plus, CommonJS has Component and npm.

**Comment by notslang** [comment]
@anthonyshort - yep... I've just spent the last ~7 hours reading about advantages and disadvantages between the 2, and how ES6 is implementing modules.

I actually really liked the idea of loading modules asynchronously in the browser. And after learning RJS, it looked like the holy grail of module loading... being able to work everywhere, exactly the same. But after reading your's and @timoxley's comments, and other articles (especially: http://tomdale.net/2012/01/amd-is-not-the-answer/) I've come to the conclusion that CJS is much more practical... which eliminates the the only reason I was hesitant about adopting the Component approach for my own projects.

Thanks for the replies!

**Comment by timoxley** [comment]
:+1:

**Comment by anthonyshort** [comment]
Just want to point out that RJS can also load CommonJS modules, so there really isn't any reason to use AMD :P

Good luck!
