### ISSUE TITLE
Syntax error when browser parses build.js

### ISSUE THREAD

**Issue by bodokaiser** [componentjs/builder.js#111]
Hello,

I am experiencing a syntax error in chrome canary with latest versions of component.

Chrome shows me the syntax error at this line:

```
require.register("component-path-to-regexp/index.js", Function("exports, require, module",
"\u001f�\b\u0000\u0000\u0000\u0000\u0000\u0000\u0003uS�n�0\f��+ؠ�$'��k���a;n�v��Uu�X�#\u0019�ܴK��#%;K�·8\u0012\u001f\u001f���\"�&�����z\u0005��\fM���F=w�9F��dkW}�r��.x�\b���ɤH\u0014_���V�V\u0010\u001a\u0005\u001b��LD�\u000fN�͜�8\u0015zg�\u0004\u0012�o�V:@^����P=B�\u0018P�.��tN��ol߮�A!��j\u0015�v��\u001b�鶅ښ ��e�V֪��J9B�R/`�V�\u001c�X*%�]�`Z�^�b�W�HAP�6'��\u0014C�c?�:��\u0016`�#Nr@yP��\ruw�3\u0012�\t5�cm����ã��\u0011l\u0017p�\u0014K��>Q\u001e#^v\u001a:��dPxF\u0003ֽ�)������iB?\u001f)\u0005�'0\u001eШ�\u0012\u001c\u000e�?^c�\t���x\u001dО���tw\u0002��u8G�\u000b\nSE\f�\u0017\u0012/oq\u0005\u0000�\u001abG��\u000f��ʮ!\r%\u0006�c�D�\u001e4j&\"\u0004�\u0019g0����j�ف\t�`��Z\u0003*\t\u000f\u00009n@-\u0003�EæK`\f\u0016���\tDcܩ�\u0017����\u0017�9\u0016(\u0017ś(�\nQ�*\u0017��W��@\u0010�x���\u0010\u0014(�'\u0013%1����s���hŚ>�\u0010-�C-;\\u5Z#[�\u0005�\u0004\u0019D\u000fɗw�o�>n�\"�%�d�����>��Q�n��R�Pz��\f%I�a�\u0018\u001b΀���o\u0014%�%U(\u000b5�!�������R)��9�{\fP�aV�\u0019�WWȼ�+��Y)X��1�����}&��\u0010�F��\u0002��ƲA�����e�\u0015Et��.?�q�ʒ�y�m�]\u001aT3j7�+gw���<�\f�;}1�ji��/�\u000f/���>\u0005\u0000\u0000//@ sourceURL=component-path-to-regexp/index.js"
));
```

I think the invalid unicode chars should not be there?

Full source code available here: https://github.com/bodokaiser/bankingjs/pull/29

PS: Pleased to see something like component out here :)

**Comment by tj** [comment]
this is currently an issue with superagent (used by component-install) with recent nodes, node changed its unzipping api or something so we'll have to fix that to get unzipped contents working again

**Comment by bodokaiser** [comment]
@visionmedia If you have more important things to do and it not too specific I could take a look myself tomorrow if I can get a more detailed scope (which files to look at).

**Comment by tj** [comment]
it should be something pretty simple, I dont think node intentionally changed the api or anything, or if they did probably not very much

**Comment by bodokaiser** [comment]
You already fixed it yourself :(

Though thank you for that. May be I can be somewhere else part of a new age of web development :)

**Comment by tj** [comment]
fixing it caused another bug :( one of the tests fail now

**Comment by bodokaiser** [comment]
pull request is online for that
