### ISSUE TITLE
exclude tests from build in production

### ISSUE THREAD

**Issue by bodokaiser** [componentjs/builder.js#112]
Hello,

it would be great to define development files in component.json:

```
{
  "name": "view",
  "main": "lib/index.js",
  "scripts": ["lib/dep1.js", "lib/dep2.js"],
  "devScripts": ["test/test1.js"]
}
```

**Comment by jonathanong** [comment]
why? `component.json` is generally for consumption.

**Comment by tj** [comment]
ah I think this is a duplicate, but I personally just use regular script tags for test scripts, bypassing component all together, closing since it's a dup though
