### ISSUE TITLE
Can't make standalone builds of hyphenated modules

### ISSUE THREAD

**Issue by ForbesLindesay** [componentjs/builder.js#12]
``` javascript
window.data-table = require("data-table");
```

Should either be:

``` javascript
window['data-table'] = require("data-table");
```

or

``` javascript
window.dataTable = require("data-table");
```

The later nicely follows the same conventions as `element.dataSet` so I'd support that one, but I don't mind.

**Comment by ForbesLindesay** [comment]
Actually, I've been thinking about this... I think we should add a field to component.json for "standalone name"  That way you could set this explicitly.  It's likely that you'll frequently want a longer name for standalone because there's no neat nesting of dependencies.

I also think that for modules that have side-effects, there should be an option to build in standalone mode without assigning the result of the require to anything, so instead of `window.moduleName = require('moduleName')` we just add `require('moduleName'`.  We could do that by letting you set "standalone name" to something special like `null` or `""` or `"[none]"` which are all not likely to conflict with any real name choices (because of the square brackets, if you had a library called `none` you'd assign it to `window.none`)

**Comment by tj** [comment]
nah, I want to keep things as simple as possible, root level packages need to be namespaced to disambiguate, but there's almost no times where you'll actually require the "canonical" name. Tests for example might be one place, and that's _only_ if you dont implement your test suite as a component, which would be more ideal in which case there would never be a case for doing `require('component-jquery')` etc

**Comment by tj** [comment]
plus the whole idea of components is to get away from globals

**Comment by ForbesLindesay** [comment]
Yeh, I get that, was just thinking that as an interim measure, I want to build libraries using component, for component, but I'd really like the  resulting code to be usable outside of component.

**Comment by tj** [comment]
oh right sorry i didn't read the title, missed the "standalone" part, I agree that should be changeable, but via `--standalone NAME`

**Comment by tj** [comment]
https://github.com/component/component/issues/34

**Comment by ForbesLindesay** [comment]
Cool, thanks :)

**Comment by tj** [comment]
im really bad at reading things lately hahahaha, apparently im a very selective reader, I saw the window assignment and was like WHA
