### ISSUE TITLE
Automatic vendor-prefixing

### ISSUE THREAD

**Issue by hkjels** [componentjs/builder.js#126]
I recently made [component-autoprefixer](https://github.com/hkjels/component-autoprefixer), but I can see an issue with it. Relying on it, you will have to document for every component that it needs to be used. I believe prefixing is something the builder could handle natively as it does belong in build-land and it's very unlikely that you will not want them, if so; we could have a flag for turning them off I guess.

**Comment by anthonyshort** [comment]
It would be really nice having it do this, but it is not really related to Component, so I can see how it wouldn't belong in the project.

The problem with any of the plugins is that you need to know to use them, that's why they generally aren't used in public projects. I've used them internally, where as part of the build process you can just make sure the plugin is used. For public Components, I'd just avoid them.

**Comment by hkjels** [comment]
I think you actually pin-point why this should be in the builder. Most of the Component-plugins would fraction the community with adding new languages to the mix, not cool. This however is pure css that corrects an impurity brought on by browser-vendors. Not having it in the builder means that every web-dev will have to take them into consideration which actually sets the bar higher for getting started with web development and you'll repeat yourself over and over for no good reason.

**Comment by hkjels** [comment]
I was just about to comment that `component/html`-plugin should have been in the native builder as well, only to realize that it now is in the new version of Component.

**Comment by timoxley** [comment]
Perhaps a solution would be to allow components to inject steps into the build.

**Comment by anthonyshort** [comment]
Another issue with the auto prefixer is selecting the browsers to support with it. That adds a whole bucket of other problems.

**Comment by hkjels** [comment]
I'm not sure what would be the best solution.  We could have a `browsers`-field in `component.json` where you specify browser-support. Default would be `> 1%, last 2 versions, ff 17, opera 12.1` I guess. It's not an optimal solution, but ignoring the issue altogether is worse I think. The same field could be picked up by a CI for testing.

**Comment by anthonyshort** [comment]
That would actually be quite awesome. I would definitely like to have it auto-prefix the CSS that way. 

Alternatively, you could just fork the builder and make your own tool that you use internally. Component is supposed to be just a "spec" with various implementations. You could even use the component builder.js in your tool and just add features to it using the hooks. I've been thinking of doing this for a while to manage internal requirements at work.

**Comment by hkjels** [comment]
Well. I don't have any issues using `component-autoprefixer` as it is, the issue is others not knowing that you need to use it. I believe some things; like vendor-prefixes, we can agree upon should be unnecessary to deal with. I'd say [pure-css](https://github.com/ianstormtaylor/rework-pure-css) is a good candidate as well, since the spec is already agreed upon and just not implemented by all vendors. Unlike client-side polyfill's, these won't hurt performance, so to me they are no-brainers.

Another way to tackle the problem would be to have rework on by default and have instructions about rework-plugins per component. I quite like that idea, however rework is pretty flexible, so it can lead to fraction unfortunately.

**Comment by jonathanong** [comment]
-1 like what anthony said. components shouldn't use CSS that requires prefixing anyways - at that point, your component is probably too opinionated.

**Comment by hkjels** [comment]
So your saying we shouldn't use transitions or gradients etc, really? All modern browsers support them, but their syntax may vary, so using a build-step until the spec is agreed upon is totally fair if you ask me. Not using them is a purist vision that just hurts the final outcome. Using these features moves the web forward, so do you really believe it's a good idea to ignore them entirely?

**Comment by micky2be** [comment]
I would not use an autoprefixer.
Browser behave differently depending what you wanna do. 
For example the way I use border-image doesn't work the same way in webkit than Firefox. 
I need to make the CSS that fit for Firefox. 

Having a plugin is fine but I don't wanna see an autoprefixer in builder.js. I need to stay in control.

**Comment by timoxley** [comment]
I don't think this needs to go into core (it's easy enough to opt in), but I think you're missing the point of an [autoprefixer](https://github.com/ai/autoprefixer) @micky2be. 

> For example the way I use border-image doesn't work the same way in webkit than Firefox. 
> I need to make the CSS that fit for Firefox.

This is exactly what the autoprefixer does for you.

```
> echo 'body { border-image:url(border.png) 30 30 round; } ' | autoprefixer
```

``` css
body {
  -webkit-border-image: url(border.png) 30 30 round;
  -o-border-image: url(border.png) 30 30 round;
  border-image: url(border.png) 30 30 round;
}
```

And if you want to write custom declarations for a specific browser, you can! The prefixer isn't going to strip them out:

```
> echo 'body {  -webkit-border-image: url(border.png) 40 40 round; border-image:url(border.png) 30 30 round;} ' | autoprefixer
```

``` css
body {
  -o-border-image: url(border.png) 30 30 round;
  border-image: url(border.png) 30 30 round;
  -webkit-border-image: url(border.png) 40 40 round;
}
```

You are still in control, the autoprefixer simply augments standards based css until the browser vendors get their shit together, saving you the hassle of researching and remembering which prefixes are still necessary and what their different syntaxes are etc.

**Comment by hkjels** [comment]
@timoxley If it's not in core and there's no error thrown, then you might just think that the component is broken when you try and use it. I think we need a way to express build-step dependencies or have it be in core. Obviously, you could simply do this to your source before you push, but then your just garbling your code unnecessarily and everyone has to do it all over for each and every component.

**Comment by timoxley** [comment]
Maybe the simplest solution is to automatically invoke a recursive Make, called at the start of `component build`, then you could reliably point at your built files as your main js/styles etc in your component.json. Hm, I recall this was discussed before though and was tossed due to too much magic/coupling to Make perhaps?

**Comment by jonathanong** [comment]
@hkjels I'm saying your components generally shouldn't have them because they are supposed to have minimal styling and opinion. You should let the end developer decide on the opinionated effects such as transitions and gradients. Most of the components I use don't use prefixes, but if they do, there are not enough prefixes to warrant autoprefixer.

plus, this would be an over optimization. if your component uses prefixes, just add them all. if the end user wants to optimize it, they can choose to auto prefix.

**Comment by hkjels** [comment]
I do see your point, and it's a good one. There are cases like themes and components like [hkjels/input-search](http://hkjels.github.io/input-search/) where the output, although not final, still has some visual snax applied. But I guess I can live with applying prefixes manually for now.

**Comment by timoxley** [comment]
> I'm saying your components generally shouldn't have them because they are supposed to have minimal styling and opinion. 

@jonathanong What about the components that are supposed to add styling and opinion e.g. "themes"?

**Comment by timoxley** [comment]
haha, actually don't worry, let's let this bike shed die.

**Comment by jonathanong** [comment]
@timoxley i don't think anyone uses themes :P
