### ISSUE TITLE
idea: replace `require()` calls with full component name

### ISSUE THREAD

**Issue by jonathanong** [componentjs/builder.js#130]
ex:

``` js
require('delegate') -> require('component/delegate#0.1.0')
require('component-delegate') -> require('component/delegate#master')
```

Then don't even bother aliasing at all. All dependency checking will happen at build time. We can resolve the names based on the dependencies. 

Only edge case i can think of is when users do `*` with their dependencies, then we can resolve the dependency at `require()` time.

Of course, this won't work with any components that do silly stuff with their require calls.

**Comment by tj** [comment]
yeah that's the plan, screws over dynamic requires but I can't see any practical use-cases for that on the client side anyway

**Comment by tj** [comment]
we don't need a require implementation at all if we do that it would just be `var delegate = modules['component/delegate@whatever']`

**Comment by jonathanong** [comment]
Would still like a require implementation though since I require components outside the build, but I guess it'll be much simpler and could be opt in.

**Comment by tj** [comment]
didn't bother going with building the dep tree first, but that'll be the next optimization for sure

**Comment by jonathanong** [comment]
Yeah I'm working on a "resolver" for both locals and dependencies. Want to wait until the registry is up though.
