### ISSUE TITLE
require.alias is taking too much space of my build file

### ISSUE THREAD

**Issue by shallker-wang** [componentjs/builder.js#131]
`require` algorism of builder.js is becoming a burden of my build.js file.
If the total size of my build.js file is 10KB, then `require.alias` and `require.register` are taking 2KB of it, which means 20% oversize my actual JS code.
Is there anyway to reduce the repetition rate of the `require` at the end of the build file?

**Comment by shallker-wang** [comment]
as same as #55 
I wrote a similar common-js modules [bundler](https://github.com/shallker-wang/modular-js/blob/master/lib/client.js) for client side before. It didn't seem to have this problem. It was inspired by [stitch](https://github.com/sstephenson/stitch).

**Comment by tj** [comment]
dup

**Comment by tj** [comment]
there's only a few tiny things we lose from not doing aliasing, but it's worth it haha so we'll definitely be getting rid of them
