### ISSUE TITLE
rewrite with generators / co

### ISSUE THREAD

**Issue by tj** [componentjs/builder.js#133]
so shit actually makes some sense

**Comment by buschtoens** [comment]
Wohoo!

**Comment by anthonyshort** [comment]
:+1:

**Comment by jonathanong** [comment]
you gonna do this now and use `gnode` or when node 0.12 comes out? `gnode` is freaking slow

**Comment by tj** [comment]
haha yea forgot about the node restriction :(

**Comment by anthonyshort** [comment]
The builder is supposed to work in the browser?

**Comment by jonathanong** [comment]
@anthonyshort don't think so

@visionmedia we can still do this. require > 0.11.3 and fallback to gnode. wrap the process in `--harmony-generators` if necessary. ideally, we wouldn't release this until node 0.12 though

**Comment by tj** [comment]
going to rewrite it Go eventually anyway so this is all good for now

**Comment by jonathanong** [comment]
in golang? well that was unexpected

**Comment by tj** [comment]
easier to ship binaries around, installing node/npm for component is a little weird

**Comment by jonathanong** [comment]
i guess i'll have a reason to learn golang when that happens then.

close this for now then?

**Comment by tj** [comment]
we could probably re-open once most people are on 0.12.x

**Comment by ianstormtaylor** [comment]
hhahah i wish there was a like button for

> well that was unexpected

**Comment by tj** [comment]
hahahaha
