### ISSUE TITLE
should be streaming 

### ISSUE THREAD

**Issue by jonathanong** [componentjs/builder.js#138]
Streaming API. Plugins should basically be a transform streams. It should itself be a readable stream.

**Comment by tj** [comment]
ewww no

**Comment by tj** [comment]
that just complicates everything, they're not really streams to begin with, we gain nothing from backpressure, and most (rework etc) are also non-streaming, and would also gain nothing from being streaming so we would just have to buffer anyway

**Comment by jonathanong** [comment]
yes, each file is a stream, and you write to a file which is a stream. yeah, there's really nothing to gain from back pressure. yes, kind of sucks for CSS since most of us use rework, but it'll work for plain JS.

i know you think streams are confusing, but i can do it without `batch` or any crazy emitter handling. for me, it's simpler, but i guess i would have to show you.

**Comment by tj** [comment]
they just suck haha, they're not confusing, C has streams too but they're actually done right, there's nothing to gain here, if flow control is the concern that's not a reason to take a meaningful api and turn it into a shitty stream api

**Comment by tj** [comment]
streams should be an implementation detail, _not_ the implementation.

**Comment by jonathanong** [comment]
they do suck. they have a high learning curve. doesn't help that from what i've read, es6 streams return promises ~_~

not concerned with flow control. it'll be easier to read / understand (if done correctly). there are wayyy more important things to fix though, so whatever haha

**Comment by tj** [comment]
yeah, builder is admittedly poorly written and confusing right now haha but I don't think streams would help at all. Just me trying to make it a "class" didn't work out well, too much state involved, and of course the callbacks don't help
