### ISSUE TITLE
Aliasing non-main scripts

### ISSUE THREAD

**Issue by ForbesLindesay** [componentjs/builder.js#14]
Because we take all the scripts when doing aliasing [here](https://github.com/component/builder.js/blob/master/lib/builder.js#L298) we are creating lots of aliases that don't actually work anyway.  We end up directing all those files to the index.js file anyway, so it's redundant.  This could alow us to change things to:

``` javascript
var aliases = (function () {
  var name = builder.conf.name;
  // TODO: remove special-casing root
  var alias = self.root ? 
      self.conf.name + '/deps/' + name
    : self.name + '/deps/' + name;
  var js = 'require.alias("' + builder.name + '/index.js", "' + alias + '");\n';
  return js;
}());
```

This will simplify our move to not hard-code `index.js`

**Comment by ForbesLindesay** [comment]
I suggest we also want to load the JSON for everything, rather than assigning a name property in the constructor, since that name can't be relied upon.

**Comment by tj** [comment]
should be resolved now
