### ISSUE TITLE
Feature request (or maybe just confusion)

### ISSUE THREAD

**Issue by jasonkuhrt** [componentjs/builder.js#140]
I have a use-case for I think `addFile` that isn't working.

I have a plugin that will add a synthetic file to the final build. I want other scripts to be able to include this added file as if it were a dependency, so `require('env')`, not `require('./env')`.

I cannot seem to figure this out. It appears that in addition to `addFile` I need to use aliasing?

**Comment by jonathanong** [comment]
if you want to `require` anything without any relative paths, the best thing to do is make it its own (local) component.
