### ISSUE TITLE
still need aliasing mechanism for .main

### ISSUE THREAD

**Issue by tj** [componentjs/builder.js#141]
just realized this will break stuff like reactive with lib/index.js and then relative requires. so we either need to rewrite those requires or use aliasing.

**Comment by tj** [comment]
kind of wish we forced ./index.js to always be the entry point, no reason not to, if it's anything but that it's usually just unclear or confusing

**Comment by bmcmahen** [comment]
agreed. I don't think I have ever _not_ used index.js as main.

**Comment by tj** [comment]
fixed in 98e8c4a6a927f40bd6ac1629a97a1258da534c5a

but yup haha wish we never added support for main

**Comment by micky2be** [comment]
Please don't force it to index.js
It will break our apps and our flow.
