### ISSUE TITLE
recent change broke alias behavior with local components

### ISSUE THREAD

**Issue by matthiasg** [componentjs/builder.js#144]
The recent change in alias behavior broke the scenario of having a local component (as defined in the `local` section of the config) with a different folder name as that components name.

Basically the name of the local component and the name of the folder that component is located in has to be identical now.

I think this is not a big deal I just renamed my local deps to be consistent and think its better that way for me, but since it might not have been intended or break other peoples code i opened this issue.

Example:

```
...
local: [ 'myComponent']
....
```

where the component `myComponent` was located in a folder `company-myComponent` with a component.json that then declares the name to be myComponent

**Comment by pgherveou** [comment]
Yop
just noticed that too 
As an example I had deps on "guille/ms.js" I know need to replace my require calls 

``` js
// before
var ms = require('ms')

// now
var ms = require('ms.js')

```

Also I noticed that you need to require full qualified module name when calling it from root level
In my test files for example I need to replace

``` js
// before 
var chai = require('chai'),

// now
var chai = require('chaijs-chai')
```

**Comment by jonathanong** [comment]
> name of the local component and the name of the folder that component is located in has to be identical now.

i think this should be a requirement. it doesn't make sense to do anything otherwise. it just confuses everybody.

**Comment by tj** [comment]
for locals I agree, but if guille/ms.js etc requires the full repo name that's broken, that'd be akin to `require('node-co-body')` if you happen to want to prefix your repos

**Comment by tj** [comment]
ah ok it occurs when the repo name is completely different. we have to build the dep tree to resolve those properly, otherwise we have no `.name` to use, but I'll hack it for now

**Comment by tj** [comment]
meh just going to revert 0.19.x for now, no point fixing a half-implemented thing, we really need to do the tree
