### ISSUE TITLE
Add a header `// generated by component-js` so that it doesn't show up in github diffs

### ISSUE THREAD

**Issue by vendethiel** [componentjs/builder.js#145]
This could either be added in the `component-require` package or added here as a `"banner"` prop passed to `fn` ? (and adding that [here in component-build(1)](https://github.com/component/component/blob/master/bin/component-build#L117))

**Comment by jonathanong** [comment]
oh what. that's cool!

**Comment by tj** [comment]
I think I'll have to decline actually, because this still makes inspecting commits on your machine super ugly, I'd rather see a big glaring nasty diff on github so people can re-commit

**Comment by vendethiel** [comment]
what? this doesn't change anything when you're on your own machine

**Comment by tj** [comment]
I don't want to mask it in github diffs, because it's still a problem when inspecting locally, build products shouldn't be included in pull-requests
