### ISSUE TITLE
Treat main as index.js

### ISSUE THREAD

**Issue by ForbesLindesay** [componentjs/builder.js#15]
If we add in the following alias [here](https://github.com/component/builder.js/blob/master/lib/builder.js#L286):

``` javascript
batch.push(function (done) {
  var main = self.conf.main || 'index.js';
  //todo: special case root for self.name to use self.conf.name instead
  done(null, 'require.alias("' + self.name + '/' + main+ '", "' + self.name + '");\n');
});
```

And change our aliasing [here](https://github.com/component/builder.js/blob/master/lib/builder.js#L304) to:

``` javascript
var js = 'require.alias("' + builder.name + '", "' + alias + '");\n';
```

And swap the order of aliasing [here](https://github.com/component/builder.js/blob/master/lib/builder.js#L310) to:

``` javascript
done(null, str + aliases);
```

That would make main override the index.js default file name.  I really need this, so if those changes would be acceptable then please can we get this sorted?

It should also let us simplify `require.resolve` to:

``` javascript
require.resolve = function(path){
  var orig = path
    , reg = path + '.js'
    , regJSON = path + '.json'
    , indexJSON = path + '/index.json';

  return require.modules[reg] && reg
    || require.modules[regJSON] && regJSON
    || require.modules[indexJSON] && indexJSON
    || require.modules[orig] && orig
    || null;
};
```

**Comment by tj** [comment]
I think you're on the right track, but from what I see we'll still need some sort of boolean to mark a file as main. `require.resolve` would need some logic to know that `require('foo')` is really `foo/main.js` and not `foo/index.js` etc

**Comment by ForbesLindesay** [comment]
That's just a matter of choosing order surely? If someone executes `require('foo')` we should attempt to load:
- `foo`
- `foo.js`
- `foo.json`

In that order (which may not be what resolve currently does).  We're then creating an alias from `foo` to `foo/main.js` which causes that to be loaded first.

**Comment by ForbesLindesay** [comment]
Perhaps `require.resolve` should be:

``` javascript
require.resolve = function(path){
  var orig = path
    , reg = path + '.js'
    , regJSON = path + '.json'
    , index = path + '/index.js'
    , indexJSON = path + '/index.json';

  return require.modules[orig] && orig
    ||require.modules[reg] && reg
    || require.modules[regJSON] && regJSON
    || require.modules[index] && index
    || require.modules[indexJSON] && indexJSON
    || null;
};
```

That way we'd pick up `foo` as an alias for `foo/main.js` before picking up the (incorrect) `foo/index.js`

**Comment by tj** [comment]
`require('foo')` would always fail, since it has to be within that foo dir, `require('foo/foo')` etc

**Comment by ForbesLindesay** [comment]
OK, now I'm confused, I think foo may be a bit too abstract for me to process at the moment:

```
foo
    \components
        \component-bar
            main.js
            package.json (contains key "main" value "main.js")
    index.js
    package.json
```

Say `component/bar` is a dependency of `foo`.  In `foo/index.js` we `require('bar')`

`require.resolve` will look up `foo/deps/bar` which is an alias of `component-bar` which is in turn an alias of `component-bar/main.js` which exists and is loaded.

If it wasn't for the `main` field in `package.json`, that last alias would instead point to `component-bar/index.js`.

**Comment by ForbesLindesay** [comment]
Am I making sense?  Do you agree with #14 that we shouldn't provide aliasing for anything but the main script?  The aliasing wouldn't actually work anyway for non-main scripts at the moment.  If you're happy with both then I can submit a pull request?  There are so many libraries I want to get converted at the moment that I can't because of this.

**Comment by tj** [comment]
I dont think aliasing will work, we need to check say `require('page')` then if component.json had mentioned a main then when we're resolving we resolve `require.mains['page'] || regular resolve stuff here`, something like that. Just giving it higher precedence than a index.js check

**Comment by ForbesLindesay** [comment]
When I tested it out the aliasing mehtod worked fine.  The odd thing with what your suggesting is that you'd need to alias the mains such that you had:

``` javascript
require.mains['component-tip'] = require.modules['component-tip/main.js'];
require.mains['foo/deps/tip'] = require.mains['component-tip']
```

You'd then need to update `require.resolve` and `require.relative#resolve` to look for it in `require.mains` before `require.modules`.  All in all it just seems weird and complex, especially when we already have `require.alias`.

I'm really not clear why you don't want to use `require.alias` for this?

**Comment by tj** [comment]
I'll read over your suggestion again later maybe I missed something

**Comment by tj** [comment]
ah ok, read it again and I get what you're going for, sounds good to me
