### ISSUE TITLE
version 0.12 pushed to npm does not support hook and not in github

### ISSUE THREAD

**Issue by matthiasg** [componentjs/builder.js#156]
it seems npm has version 0.12 which i just installed .. that version does not even have the 'hook' function, thus its not usable for me ... sadly 0.12 is also not on github so it wasnt apparent at first for me where the hook function was removed (because it wasnt on github yet)...

was that a mistake ?

**Comment by tj** [comment]
0.12 has a different api https://github.com/component/builder.js/blob/master/History.md#0120--2014-01-27

we still need to make the new version a bit more friendly, that's why it's not at a 1.0 yet

**Comment by matthiasg** [comment]
All for it.. It was just weird to see it on npm this early .. Since component is a global cli module there is no dependency semver protection when you just npm install .. Unlike installing a normal module dependencies ... And therefore when plugins don't work it takes some time to figure out what's happening... 

-----Original Message-----

**Comment by tj** [comment]
we should have the cli pegged at 0.10.x

**Comment by tj** [comment]
yup: https://github.com/component/component/blob/master/package.json#L18
