### ISSUE TITLE
Completely broken?

### ISSUE THREAD

**Issue by stephenmathieson** [componentjs/builder.js#158]
Using component-builder@0.12.0:

``` js
var builder = new Builder(path);
builder.build(function (err, res) {
  if (err) throw err;
  var js = res.require + res.js;
  var css = res.css;
  console.log(js);
  console.log(css)
});
```

yields:

```
NaN
undefined
```

Are the dox out of date, am I doing something wrong, or is this thing completely broken?

**Comment by tj** [comment]
0.12.x has a different api, 0.10.x is the one you want to stick with for now

**Comment by tj** [comment]
(breaking change is mentioned in the changelog), it would have been a 1.0 but we have some more changes to make

**Comment by stephenmathieson** [comment]
gotcha, thanks
