### ISSUE TITLE
Update API docs

### ISSUE THREAD

**Issue by necolas** [componentjs/builder.js#161]
In `0.12` breaking changes where made and the docs seem out of date. I get `TypeError: Object #<Build> has no method 'hook']` for plugins when using `0.12`.

**Comment by tj** [comment]
we have to break it a bit more right away, I'll add a note

**Comment by buritica** [comment]
Hey guys, any update on this? Or better yet is there any existing project that uses this up to date version? I had used https://github.com/component/component.io/blob/master/lib/build/index.js as a reference, but it's now out of date.
