### ISSUE TITLE
css build bug

### ISSUE THREAD

**Issue by chemzqm** [componentjs/builder.js#174]
Using builder.js 0.12.0 get url like this:

``` css
 background-image: url('url(data:image/png;base64,iVBOR
```

Same issue as https://github.com/component/component/issues/550

**Comment by azhang** [comment]
Latest version has fix. https://github.com/component/builder2.js/pull/49—

**Comment by chemzqm** [comment]
I've reinstalled the dependencies of components and find it's still using 1.1.2, it works when I upgrade to 1.1.3
