### ISSUE TITLE
lowercase component repos

### ISSUE THREAD

**Issue by ForbesLindesay** [componentjs/builder.js#21]
If you require a library like `moment` which I now have a component-comptible verison of at `ForbesLindesay/moment` from outside any component, it can go badly.  eg.

``` html
<script src="build/build.js"></script>
<script>
var moment = require('ForbesLindesay-moment');//this doesn't work
var moment = require('ForbesLindesay-moment/moment.js');//this must be used instead
</script>
```

Also, should we lower-case all names at some point, not sure where's best to do that?

**Comment by tj** [comment]
ah yeah we definitely should, we'll need to add the lowercasing bit to the spec as well. we'll have to do it in builder and on install in component/component. I should be setting up aliases for the "root" component as well, there's no `require('ForbesLindesay-moment/index.js') alias in the build.js?

**Comment by tj** [comment]
had this with superagent as well https://github.com/component/builder.js/issues/26, definitely a bug, I'll rename this issue to lowercasing

**Comment by ianstormtaylor** [comment]
assuming this is fixed now
