### ISSUE TITLE
Custom main generates bad alias

### ISSUE THREAD

**Issue by creationix** [componentjs/builder.js#22]
Somewhere in https://github.com/component/builder.js/blob/master/lib/builder.js#L339-343, it's using the wrong component name for the alias.  I was trying to make a simple app with my component stuff living in a folder called "static".  I named my main app component "app". 

See this gist for my files and the generated build.js https://gist.github.com/43927d6c31d83372a7c8

The last line in the build is in error.  It's using the folder name for the component name instead of the specified name in the component.json.

**Comment by creationix** [comment]
Note that the module is correctly registered as

``` js
require.register("app/client.js", function(module, exports, require){

});
```

But is incorrectly aliased as:

``` js
require.alias("static/client.js", "static/index.js");
```

**Comment by tj** [comment]
shit, copy/paste fail. once I have the linter up and running and `repo` is always defined in the component.json we'll use that instead of the dirname, ill add a test and patch this up thanks for the report
