### ISSUE TITLE
"repo" instead of dirname

### ISSUE THREAD

**Issue by tj** [componentjs/builder.js#23]
currently we assume the components were installed and thus have the correct name but this may not always be the case, it would be safer to generate aliases based on `repo`

**Comment by nickjackson** [comment]
I am using components to structure my app and therefore a lot of my components are private and I can't host them. As a result I don't set `repo`.

**Comment by tj** [comment]
hmm yeah good point, it's mainly a problem for the root component, which tim reported but that's fixed now so maybe this wont be a problem in practice, i'll close for now
