### ISSUE TITLE
Minify Names

### ISSUE THREAD

**Issue by ForbesLindesay** [componentjs/builder.js#27]
It would make for much better efficiency if we had a good system for somehow minifying the path names in the built output.  Things like UglifyJS don't do a great job of minifying the names of things in the output of builder.js.  There's not a lot you can do when it's not standalone, but when it is, we could minify all path names to a few characters if we're clever.

**Comment by tj** [comment]
no reason, gzip takes care of all redundancy

**Comment by ForbesLindesay** [comment]
Fair enough.  I wondered if it might also slow down runtime performance to compare with longer keys.
