### ISSUE TITLE
Change require.register to require.define

### ISSUE THREAD

**Issue by paulmillr** [componentjs/builder.js#30]
Modules are wrapped to wrapper and registered via this currently

``` javascript
require.register("module/path", function(module, exports, require) {
  // js
})
```

but it will be cooler to conform to spec http://wiki.commonjs.org/wiki/Modules/Transport/D. The result should be like this

``` javascript
require.define({"module/path": function(exports, require, module) {
  // js
}});
```

Note passing an **object** instead of just string & fn.

**Comment by paulmillr** [comment]
also i’m not sure if module js is indented currently, but it just feels nicer with it

``` javascript
var indent = function(js) {
  return js.replace(/\n(?!\n)/g, '\n  ');
};
```

so

``` javascript
require.define({"module/path": function(exports, require, module) {
// js
// js
// js
// js
}});
```

will become

``` javascript
require.define({"module/path": function(exports, require, module) {
  // js
  // js
  // js
  // js
}});
```

**Comment by tj** [comment]
indenting is potentially sketchy, if you have multiline strings etc, otherwise i'd agree

**Comment by paulmillr** [comment]
> multiline strings

``` javascript
var indent = function(js) {
  // Emulate negative regexp look-behind a-la (?<!stuff).
  return js.replace(/(\\)?\n(?!\n)/g, function($0, $1){
    return $1 ? $0 : '\n  ';
  });
};

// The code.

var a = "string\
shit\
crap\
meh";
var b = a + a;

indent('\nvar a = "string\\\nshit\\\ncrap\\\nmeh";\nvar b = a + a;')

// # =>
  var a = "string\
shit\
crap\
meh";
  var b = a + a;
```

**Comment by paulmillr** [comment]
(irrelevant, but interesting) a bit of clarification why objects are used (I forgot it every time I revise my code): it just makes stack traces awesome.

for example, node-browserify compiles stuff to this:

``` javascript
// string, fn; not obj
require.define("module/path": function(exports, require, module) {
  // js
});
```

compare stack traces w obj and w/o obj:

![](http://f.cl.ly/items/1J2Z280i1m360q070e0k/obj.png) ![](http://f.cl.ly/items/453t163L3A3h412M2d3X/no-obj.png)

**Comment by tj** [comment]
the stack trace portion shouldn't be a big deal now that we have source url support

**Comment by paulmillr** [comment]
interesting. sourceurl ain’t worked for me in the past, my initial implementation was based on it. I think it worked only with `eval`-ed fns.

does it actually work for you now?

**edit** ah, my stupid. just realised that the stuff is based on sort-of-eval `Function`. ye it should work now, nice

**Comment by tj** [comment]
yup! I tried it out, in `--dev` we've got the builds wrapped with function evals now, I've left them out in production builds until we can analyse any potential performance degradation

**Comment by paulmillr** [comment]
two questions:
1. does require-component implement caching? e.g. consider `ts` module with `module.exports = new Date`. when someone will do `require('ts')`, it will be new every time, innit? The case is: node implementation caches files, right. I think we should have it too, it will reduce bugs etc.
2. there seem to be zero checks for stuff like `require('toString')`, which node handles too.

I can submit pull requests for both because I had the same experience when building @brunch and made https://gist.github.com/2958274 for fast-and-dirty module testing.

**Comment by tj** [comment]
yup they're cached, and nope no special prop handling ATM
