### ISSUE TITLE
"main" isn't followed by development dependencies

### ISSUE THREAD

**Issue by matthewmueller** [componentjs/builder.js#31]
Not 100% sure what's going on here, but basically it looks like the aliasing is a bit off.

If you include `component/model` as a development dependency we get duplicates:

``` js
require.alias("component-model/lib/index.js", "collection/deps/model/lib/index.js");
require.alias("component-model/lib/static.js", "collection/deps/model/lib/static.js");
require.alias("component-model/lib/proto.js", "collection/deps/model/lib/proto.js");
require.alias("component-model/lib/index.js", "collection/deps/model/index.js");
```

And `var model = require('component-model')` does not work in test files:

```
Uncaught Error: failed to require "component-model" from "root" 
```

**Comment by tj** [comment]
oops yeah i meant to re-open this one https://github.com/component/builder.js/issues/26
the fix i had wasn't correct

**Comment by matthewmueller** [comment]
ohh okay cool
