### ISSUE TITLE
calling build() twice causes it to fail the second time

### ISSUE THREAD

**Issue by matthewmueller** [componentjs/builder.js#32]
It doesn't include the dependencies or locals the second time around. 

Just for context: writing a quick middleware component and reinitializing `Builder` every time causes a lot of duplicate effort. Also, `exec('make')` ends up being pretty slow for bigger apps.

**Comment by tj** [comment]
definitely not ideal! thanks for the report. I need to fix up the js api some more I'll definitely add this to the list

**Comment by matthewmueller** [comment]
cool, thanks man

**Comment by tj** [comment]
been getting the build time down today, managed to shave about 75% of the previous time down, looking into this now

**Comment by tj** [comment]
changed my mind, it would be less error-prone to instantiate a new Builder per request, however I'll add support for passing the cache which speeds things up nicely

**Comment by ianstormtaylor** [comment]
should be irrelevant with new builder? feel free to re-open
