### ISSUE TITLE
build doesn't work if specified dir !== current working directory

### ISSUE THREAD

**Issue by matthewmueller** [componentjs/builder.js#33]
I have some `paths` and `locals` in my root `component.json` and when I try running it outside of the directory that contains that file, I end up with:

```
Error: failed to lookup "app"'s dependency "necolas-normalize.css"
```

I think it has something to do with this piece in `Builder.prototype.lookup`:

```
if (!path) return fn(new Error('failed to lookup "' + self.name + '"\'s dependency "' + name + '"'));
var dir = join(path, name);
fs.exists(dir, function(yes){
  if (!yes) return next();
  debug('found %s', dir);
  fn(null, dir);
});
```

`dir` is relative, so I fixed that by adding `dir = self.path(dir)`, but then I end up with:

```
Error: failed to lookup "visionmedia-superagent"'s dependency "component-emitter"
```

.. which is an improvement (first dependency that contains it's own dependencies). But yah - not really sure what's going on here, haha.

**Comment by matthewmueller** [comment]
Update: So it works if I use a relative path. Since builder is recursive, it needs to be relative to the root.

Here's what my dir structure looks like:

```
www/
  app/
    component.json
```

If my cwd is `www` and I say:

``` js
var builder = new Builder(path.join(__dirname, 'app');
builder.builder(...)
```

It will error out as I mentioned before. But in the same code if I add the relative path:

``` js
if (!path) return fn(new Error('failed to lookup "' + self.name + '"\'s dependency "' + name + '"'));
var dir = join('app', path, name); // <-- Add in the relative path from root
fs.exists(dir, function(yes){
  if (!yes) return next();
  debug('found %s', dir);
  fn(null, dir);
});
```

it works fine.

**Comment by tj** [comment]
hmm ill look into this next time im hacking on builder
