### ISSUE TITLE
Allow omitting namespace for dependencies in local components

### ISSUE THREAD

**Issue by karlbohlmark** [componentjs/builder.js#35]
Lets say I have 7 local modules depending on "xyz/backbone" and then want to switch over to "component/backbone".

Currently, I'll have to change this in 7 places. Since it mostly should be the case that all local modules should depend on the same backbone-module, it would be preferable if the namespace was inferred from the main component.json.

**Comment by tj** [comment]
I wont disagree that it's annoying, definitely one of the gotchas of creating a really modular application, but I think this behaviour would/could be pretty confusing, a quick grep/sed isn't too painful. More than anything the versioning gets annoying, tough call there, as soon as you delegate to some other component.json you're automatically reducing the modularity and adding more indirection

**Comment by tj** [comment]
going to close for now but I do think we should think about alternative ways to get around the bookkeeping
