### ISSUE TITLE
Add a "--copy" flag to copy images&/files instead of symlinking them to build/

### ISSUE THREAD

**Issue by ghost** [componentjs/builder.js#40]
Some backends (... django) just don't work with symlinks.

**Comment by tj** [comment]
wtf :( lame

**Comment by ghost** [comment]
:)

**Comment by camshaft** [comment]
The symlinking also becomes a problem when deploying/running on heroku. They `git clone` your project into a random folder in `/tmp` and run all of your install scripts. After it's all done, they move the contents of the temp folder into `/app` and delete the temp folder. When the server goes to look up a file (let's say `/app/build/visionmedia-my-cool-font/my-cool-font.woff`) it will point to its old location in `/tmp`.

**Comment by ghost** [comment]
Yeah, what I meant earlier was we probably should rename copyTo to symlinkTo then let copyTo do the actual copying. We then add a -P, --production option to component build that will use copyTo. I currently resolve the symlinks in make.

**Comment by camshaft** [comment]
I think that's a great idea. In development it makes sense to symlink but in prod it would be nice to just zip everything up and not worry about symlinks

**Comment by camshaft** [comment]
I've made a [buildpack](https://github.com/CamShaft/heroku-buildpack-component-deref) for heroku deploys to overcome this problem until it gets fixed.

**Comment by ghost** [comment]
@CamShaft nice!! how about https://github.com/component/builder.js/pull/68
