### ISSUE TITLE
set up dependency require.alias()es

### ISSUE THREAD

**Issue by tj** [componentjs/builder.js#5]
for https://github.com/component/component/issues/7

Suppose our app's "boot" component started things off with pet / user listings,
we might have a simulated fs like this:

```
./user
  ./deps
    ./inherit -> component-inherit

./animal
  ./deps
    ./inherit -> component-inherit

./component-inherit

./pet-list
  ./deps
    ./pet -> pet

./user-list
  ./deps
    ./user -> user

./boot
  ./deps
    ./pet-list -> pets-list
    ./user-list -> pets-list
```

 Now for the sake of argument if "component/inherit" was used for animal, and "learnboost/inherit" was used for user it would simply resolve like this:

```
./user
  ./deps
    ./inherit -> learnboost-inherit

./animal
  ./deps
    ./inherit -> component-inherit

./component-inherit

./learnboost-inherit

./pet-list
  ./deps
    ./pet -> pet

./user-list
  ./deps
    ./user -> user

./boot
  ./deps
    ./pet-list -> pets-list
    ./user-list -> pets-list
```

Effectively every dependency is "linked" to a root-level canonicalized component name / module definition. App-specific components such as say `./signup` should work out of the box without collision from any public deps since it's not namespaced by a GH account

**Comment by matthewmueller** [comment]
+1, love it!

So if I wanted to include `learnboost/inherit` as a dependency in `boot`'s `component.json` that would resolve to:

```
./boot
  ./deps
    ./pet-list -> pet-list
    ./user-list -> user-list
    ./inherit -> learnboost-inherit
```

Right? And `learnboost-inherit` would already be a top-level component, so no problems there.

**Comment by tj** [comment]
yup! I've tweaked the require() implementation so `require('foo')` assumes `./deps/foo`, otherwise will fail so you cannot do `require('learnboost-inherit')` for example, so this should work pretty well I think
