### ISSUE TITLE
prevent redundant aliases

### ISSUE THREAD

**Issue by tj** [componentjs/builder.js#55]
add a little helper to keep track of which have been added already, just less crap output

**Comment by stephenmathieson** [comment]
:+1:

**Comment by lancejpollard** [comment]
Does that commit look like all it takes?

How is it supposed to work in this test case:

https://github.com/component/builder.js/blob/18e1441fa4887f48d5ea5448a358444c542ef945/test/builder.js#L341-L349

the fixture looks like this:

``` js
require.register("component-jquery/index.js", function(exports, require, module){
module.exports = 'jquery';
});
require.register("component-dialog/index.js", function(exports, require, module){
module.exports = 'dialog';
});
require.register("deep/index.js", function(exports, require, module){
module.exports = 'deeper'
});
require.alias("component-dialog/index.js", "deep/deps/dialog/index.js");
require.alias("component-dialog/index.js", "dialog/index.js");
require.alias("component-jquery/index.js", "component-dialog/deps/jquery/index.js");
```

The last lines, do both end up accomplishing the same thing?

``` js
require.alias("component-dialog/index.js", "deep/deps/dialog/index.js");
require.alias("component-dialog/index.js", "dialog/index.js");
```

With the commit, it would just print the first one:

``` js
require.alias("component-dialog/index.js", "deep/deps/dialog/index.js");
```

Thoughts?

**Comment by pgherveou** [comment]
+1

**Comment by tj** [comment]
they're not different right now but they will be in the near future when we include versions

**Comment by ronkorving** [comment]
+1
Really need this to keep output sane
We're using component in game development, and the aliases are really a thorn in our eye. Happy to assist in any solution that seems preferable (and a big kudos to @viatropos for making a start).
