### ISSUE TITLE
wrapping build types

### ISSUE THREAD

**Issue by gjohnson** [componentjs/builder.js#57]
Any thoughts on the ability to wrap the output of a build type prior to having the final result? 

Couple uses cases:
- create a "standalone" into a plugin so we could use it programmatically (and leverage that form component(1))
- plugins like minifiers, etc.

**Comment by gjohnson** [comment]
not sure if hooks could be used? "after build" or something...

**Comment by tj** [comment]
hmm kinda might as well just be something you use in the .build() callback I suppose

**Comment by ianstormtaylor** [comment]
should be easier with new builder api
