### ISSUE TITLE
component build does not handle nested local components

### ISSUE THREAD

**Issue by karlbohlmark** [componentjs/builder.js#58]
There is a composability issue with the ´local´ functionality: if a component has a local dependency which in turn has a local dependency, the top level ´component build´ fails.

**Comment by karlbohlmark** [comment]
Perhaps the spec should define the precedence rules (I assume the immediate local takes precedence over the parent's)

**Comment by karlbohlmark** [comment]
Example: https://github.com/karlbohlmark/locals-of-locals

**Comment by tj** [comment]
closing because locals is likely going away https://github.com/component/component/issues/152
the more I think about it, especially in the situation you show there, these relative paths would be much clearer implementation-wise, debugging-wise, and probably dev-wise as well even if it is slightly more verbose

**Comment by tj** [comment]
going to reopen this until they're actually removed

**Comment by hkjels** [comment]
Removing locals sounds a bit drastic. What about app-specific scripts or closed source-projects?

**Comment by anthonyshort** [comment]
I'm with @hkjels, I'm using local to build components that aren't necessarily useful to anyone outside the project. What's the alternative?

**Comment by karlbohlmark** [comment]
I'd be interested to know in what direction things are going with this one.

My use case: I have a single page app with a couple of pages and a dashboard.
- The application is a component
- The dashboard is a local component
- The dashboard has widgets, I'd like for them to be local components of the local component.

Is this unreasonable?

**Comment by bjornstar** [comment]
This just bit me. I really want to use locals within locals. Any workarounds?

**Comment by tj** [comment]
@karlbohlmark sounds fine, if anything there should be more components, an app as a single component would typically be too big. Our app alone is made up of several hundred. This is definitely a bug though.

@anthonyshort just the syntax would change, lookup paths work great if you have one or two, but if people are going to want to nest things like this we can't really use lookup paths in a clean way, you'd have 20+ lookup paths which is just... weird. I would rather do relative paths to local components for those cases. The real question is whether we complicate things and support both or not, I'm not a huge fan of that idea

That discussion so far is in https://github.com/component/component/issues/152

**Comment by tj** [comment]
note to self: move this logic from component-build to here
note to self: only inherit root component's paths?

**Comment by tj** [comment]
k the way it's implemented keeps lookup paths pretty clean, it doesn't keep pushing to some global array so they can't influence each other, only the root component.json's paths are inherited
