### ISSUE TITLE
Error: EMFILE, too many open files

### ISSUE THREAD

**Issue by matthewmueller** [componentjs/builder.js#66]
Been running into this issue most the afternoon. I've been using a version of the component build middleware in the component.io repo. Server dies every 2nd request, perhaps a clean-up issue.

Probably have about 40 components. Anyone else running into this?

**Comment by tj** [comment]
shit lol wonder if it's the lack of caching for the json files, if possible a post of `lsof` would be handy, we definitely need to throttle I guess, which in node land means rewrite lots of shit!

**Comment by matthewmueller** [comment]
hmm, i'm not sure what output you're looking for `lsof` shows open files, right? is there a way to run builder and capture the files it opens with `lsof`? I could also give you `DEBUG=component:builder*` output

**Comment by tj** [comment]
oh right forgot about DEBUG, that would be fine :D

**Comment by matthewmueller** [comment]
haha, you sure? this is going to make your eyes roll over..

https://gist.github.com/4660993

**Comment by matthewmueller** [comment]
I should say, I haven't had issues after removing the component that started causing issues. My guess is the solution is ephemeral and once i start adding more components, i'll run into issues again. Here's a graph of my dependencies right now, if that helps...

![out.png](https://f.cloud.github.com/assets/170299/105562/4e79423c-69b7-11e2-8666-3760c5c7b3ae.png)

**Comment by tj** [comment]
when I started migrating our app I remember getting EMFILE as well, we can work in throttling later but for now maybe just tweak `ulimit -n largernumber`

**Comment by matthewmueller** [comment]
```
  ☁  ~ : ulimit
unlimited
```

:-/

**Comment by tj** [comment]
what about `ulimit -a` I cant remember what the default of `ulimit` is but I dont think it's `-n`

**Comment by matthewmueller** [comment]
oh you're right, my bad. it's defaulting to 256. I'll up it - thanks!

**Comment by tj** [comment]
ah nice, that's pretty low, I'll close for now but we should definitely revisit this in the future and throttle

**Comment by matthewmueller** [comment]
alright sounds good.

just for clarity, if anyone that runs into this in the future, `ulimit` isn't persistent, so you'll need to add it to your `bash_profile`. I have something like this:

```
ulimit -n 1000
```

thanks again for your help.

**Comment by cristiandouce** [comment]
So... no code fix for this?
@visionmedia I'm having the same issue right now.

But in my case, its kind of random.

I can work with the `ulimit` patch... for now. But it would be nice, IMHO, to see this fixed by the builder itself and not some OS setting patch.

What do you think?

**Comment by bmcmahen** [comment]
+1 I'm running into this problem as my app grows, particularly if I'm using `watch` to autobuild my app on changes.

**Comment by olombart** [comment]
+1
