### ISSUE TITLE
addFile this.conf undefined

### ISSUE THREAD

**Issue by bjornstar** [componentjs/builder.js#72]
I'm really enjoying using component, but I've run into a problem trying to inject some configuration data. When I try to use addFile it throws because apparently this.conf is undefined. I don't quite grok where conf comes from. 

Here's an easy way to reproduce the problem.

``` javascript
// test.js
var Builder = require('component-builder');

function test(data, cb) {
    var builder = new Builder(data);

    // vvv throws
    builder.addFile('scripts', 'file.js', 'var foo = 0;');

    builder.build(function (err, obj) {
        if (err) {
            return cb(err);
        }

        cb(null, obj.require + obj.js);
    });
}

test('.', function (err, obj) { console.log(obj); });
```

Am I using addFile incorrectly? Any hints on how to inject configuration data during runtime?

**Comment by bjornstar** [comment]
It seems like I was using addFile incorrectly. I took a look at the [transpile example](https://github.com/component/builder.js/blob/master/examples/transpile/index.js) and came up with this:

``` javascript
// test.js
var Builder = require('component-builder');

function test(data, cb) {
    var builder = new Builder(data);

    builder.on('config', function() {
        builder.addFile('scripts', 'file.js', 'var foo = 0;');
    });

    builder.build(function (err, obj) {
        if (err) {
            return cb(err);
        }

        cb(null, obj.require + obj.js);
    });
}

test('.', function (err, obj) { console.log(err, obj); });
```

Which seems to work. The readme could use a little loving, there's no mention of this magical config event as well as no mention of the append method which also makes an appearance in the example. Feel free to close this issue if you want.

**Comment by tj** [comment]
I'll doc some stuff

**Comment by tj** [comment]
the config event is just temporary btw ill get rid of that too

**Comment by timoxley** [comment]
@bjornstar you could give the readme said loving, since you've got the benefit of beginner's perspective

**Comment by bjornstar** [comment]
If the config event is going away, will there be a replacement for injecting config into the build?

**Comment by tj** [comment]
I'm open to adding it back if the use-cases are reasonable
