### ISSUE TITLE
Middleware support

### ISSUE THREAD

**Issue by richthegeek** [componentjs/builder.js#74]
Currently the "u" flag is the only way to add middleware/plugins, but this potentially causes issues where different people in a project forget to use a specific plugin. Normally of course, the use of "make" is encouraged but there are times where a targeted component build is more desired. Further, this means we have dependencies that are not explicit in the component.

To make this work (hopefully) better I suggest adding a section to the component.json spec, called "plugins" or "middleware" which is a list of plugins to use: either an array of names or a hashmap of names:options.

The behavior would be as follows:
1. component-install installs plugins from npm
2. component-build checks the existence of plugins and throws if they don't exist
3. component-build imports the plugins as -u parameters

One unclear point I can think of is if both -u and "plugins" are used, although i think that just the two are merged together (for example I can add minification when I want it only)

A philisophical point this brings up is that it is much easier to use coffeescript or stylus or whatever as the build dependencies are explicit/required... personally I don't think this is a bad thing.

**Comment by tj** [comment]
hmm yeah to be honest I'm not a huge fan of `-u`, once you get to that level it really makes more sense to use the js api, I thinking _also_ adding support at the component.json level will complicate things as well. `-u` and json really break down when you want to start passing args etc

**Comment by jonathanong** [comment]
want to remove `-u` in component v1? if we split up component into enough modules, it should be easier for people just to use the JS APIs and do whatever the hell they want.

**Comment by ianstormtaylor** [comment]
i should never have asked for `-u` in the first place it :) if we move to amir's fork then it also makes sense to nuke it

**Comment by ianstormtaylor** [comment]
i assume this is obselete with the new builder api.
