### ISSUE TITLE
builder no longer correctly resolves absolute paths in `.paths`

### ISSUE THREAD

**Issue by ravenac95** [componentjs/builder.js#91]
In some cases it might be necessary to do this in the component.json:

```
{
   ...
   "paths": [
      "/my/absolute/path/to/stuff",
      "relative/path/to/stuff"
   ],
   ...
}
```

In the current implementation of builder.js it doesn't handle this correctly. I was going to write a fix for this, however, I'm not sure if this is against the spec to have absolute paths set in `.paths` If not then I would gladly write a fix for this. It is currently breaking a custom build process for a rather large application that relies on absolute paths for ephemeral component.json files. I would prefer that builder.js knows how to handle absolute paths vs relative paths as opposed to creating a custom alternative to `component build` that feeds the correct paths to the builder.

**Comment by tj** [comment]
ah yes that's and oversight on my part, absolute should definitely work thanks for the report!

**Comment by jonathanong** [comment]
i think this is fixed
