### ISSUE TITLE
css bug?

### ISSUE THREAD

**Issue by brighthas** [componentjs/builder.js#93]
windows system , node v0.10.5

[component.json]
...

  "files":[
      "p.jpg"
  ]

[tree.css ]
  ...
    background-image: url("p.jpg");

[component build]

[build.css]
   background-image: url("\tree\p.jpg");   // ??????????????????

**Comment by tj** [comment]
https://github.com/component/builder.js/commit/2353fd240b9056104c04953d45cb9b94ad5e4986
